spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

tasks:
  validation:
    max-open-tasks-per-user: ${TASKS_VALIDATION_MAX_OPEN_TASKS_PER_USER:10}

#server:
#  port: 8081