spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: task_user
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

security:
  jwt:
    secret: ${JWT_SECRET:ODViOTZmMDYxODAzZDVlYTVhMzUyOWU2ZGU5YmM4M2M1YTdiNzUzOWU1NTBlNzEzZjdkZmJlODI3ZGVjNDFkYTQ5Mjk4YTJmODNkOTE4Y2ZhMzIyODlmOThhM2VjZjMxMGMxMmEyNTBjOWQxODViZmEzOTQ5MTRmZDBlNmEyNjc=}
    expiration-ms: 3600000
